name: Deploy to GitHub Pages

# Запускаем магию только на пуши в main
on:
  push:
    branches: develop
    
jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      # клонируем репозиторий на виртуальную машину
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4       
        with:
          dotnet-version: 9.0.x  # Or a specific version like 9.0.100-preview.1
      
      - name: Create .nojekyll file
        run: echo "" > .nojekyll  # This creates an empty .nojekyll file
      
      - name: Install WASM workload
        run: dotnet workload install wasm-tools
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
        
      # генерируем статические файлы
      - name: Publish .NET Core Project
        run: dotnet publish cs16AvaloniaTheme.Browser/cs16AvaloniaTheme.Browser.csproj -c Release --output release --nologo
  
      - name: Uploading files to gh-pages branch
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: release/wwwroot
